services:
  - type: web
    name: fotbollspredictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app_v6_8.py --server.port $PORT --server.address 0.0.0.0"
    plan: free
    autoDeploy: true
